// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	"opscore/backend/infrastructure/git"
	"opscore/backend/infrastructure/persistence"
	"opscore/backend/interfaces/api/handlers"
	"opscore/backend/usecases/repository"
	"os"
	"time"
)

import (
	_ "opscore/backend/docs"
)

// Injectors from wire.go:

// InitializeRepositoryUseCase initializes the RepositoryUseCase with its dependencies.
func InitializeRepositoryUseCase() (repository.RepositoryUseCase, error) {
	repositoryRepository := persistence.NewInMemoryRepository()
	gitManager, err := provideGitManager()
	if err != nil {
		return nil, err
	}
	repositoryUseCase := repository.NewRepositoryUseCase(repositoryRepository, gitManager)
	return repositoryUseCase, nil
}

// InitializeAPI initializes all dependencies for the API handlers, using Postgres.
func InitializeAPI(db *pgxpool.Pool) (*handlers.RepositoryHandler, error) {
	repositoryRepository := persistence.NewPostgresRepository(db)
	gitManager, err := provideGitManager()
	if err != nil {
		return nil, err
	}
	repositoryUseCase := repository.NewRepositoryUseCase(repositoryRepository, gitManager)
	logger := provideHandlerLogger()
	repositoryHandler := handlers.NewRepositoryHandler(repositoryUseCase, logger)
	return repositoryHandler, nil
}

// wire.go:

// Base path for cloning repositories
const baseClonePath = "./cloned_repos" // TODO: Make this configurable

// SlogLoggerAdapter は slog.Logger を handlers.Logger インターフェースに適応させる
type SlogLoggerAdapter struct {
	logger *slog.Logger
}

func (a *SlogLoggerAdapter) Info(msg string, args ...any) {
	a.logger.Info(msg, args...)
}

func (a *SlogLoggerAdapter) Error(msg string, args ...any) {
	a.logger.Error(msg, args...)
}

func (a *SlogLoggerAdapter) Debug(msg string, args ...any) {
	a.logger.Debug(msg, args...)
}

func (a *SlogLoggerAdapter) Warn(msg string, args ...any) {
	a.logger.Warn(msg, args...)
}

// provideGitManager is a Wire provider function for GitManager.
func provideGitManager() (git.GitManager, error) {
	return git.NewCliGitManager(baseClonePath)
}

// provideAppLogger is a Wire provider function for *slog.Logger
func provideAppLogger() *slog.Logger {

	logLevel := new(slog.LevelVar)
	envLevel := os.Getenv("LOG_LEVEL")
	switch envLevel {
	case "DEBUG":
		logLevel.Set(slog.LevelDebug)
	case "WARN":
		logLevel.Set(slog.LevelWarn)
	case "ERROR":
		logLevel.Set(slog.LevelError)
	default:
		logLevel.Set(slog.LevelInfo)
	}

	jsonHandler := slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		AddSource: true,
		Level:     logLevel,
		ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {

			if a.Key == slog.TimeKey {
				a.Value = slog.StringValue(a.Value.Time().UTC().Format(time.RFC3339))
			}
			return a
		},
	})

	return slog.New(jsonHandler)
}

// provideHandlerLogger adapts slog.Logger to the handlers.Logger interface
func provideHandlerLogger() handlers.Logger {
	return &SlogLoggerAdapter{logger: provideAppLogger()}
}
