basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the OpsCore backend service.
  title: OpsCore Backend API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: 'Enter "Bearer " followed by your JWT token. Example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
